export const provinces = [
  { id: "1", name: "Aceh" },
  { id: "2", name: "Bali" },
  { id: "3", name: "Banten" },
  { id: "4", name: "Bengkulu" },
  { id: "5", name: "DI Yogyakarta" },
  { id: "6", name: "DKI Jakarta" },
  { id: "7", name: "Gorontalo" },
  { id: "8", name: "Jambi" },
  { id: "9", name: "Jawa Barat" },
  { id: "10", name: "Jawa Tengah" },
  { id: "11", name: "Jawa Timur" },
  { id: "12", name: "Kalimantan Barat" },
  { id: "13", name: "Kalimantan Selatan" },
  { id: "14", name: "Kalimantan Tengah" },
  { id: "15", name: "Kalimantan Timur" },
  { id: "16", name: "Kalimantan Utara" },
  { id: "17", name: "Kepulauan Bangka Belitung" },
  { id: "18", name: "Kepulauan Riau" },
  { id: "19", name: "Lampung" },
  { id: "20", name: "Maluku" },
  { id: "21", name: "Maluku Utara" },
  { id: "22", name: "Nusa Tenggara Barat" },
  { id: "23", name: "Nusa Tenggara Timur" },
  { id: "24", name: "Papua" },
  { id: "25", name: "Papua Barat" },
  { id: "26", name: "Riau" },
  { id: "27", name: "Sulawesi Barat" },
  { id: "28", name: "Sulawesi Selatan" },
  { id: "29", name: "Sulawesi Tengah" },
  { id: "30", name: "Sulawesi Tenggara" },
  { id: "31", name: "Sulawesi Utara" },
  { id: "32", name: "Sumatera Barat" },
  { id: "33", name: "Sumatera Selatan" },
  { id: "34", name: "Sumatera Utara" },
  { id: "35", name: "Papua Tengah" },
  { id: "36", name: "Papua Pegunungan" },
  { id: "37", name: "Papua Selatan" },
  { id: "38", name: "Papua Barat Daya" },
]

export const cities: { id: string; name: string; provinceId: string }[] = [
  { id: "1", name: "Kota Banda Aceh", provinceId: "1" },
  { id: "2", name: "Kota Sabang", provinceId: "1" },
  { id: "3", name: "Kota Lhokseumawe", provinceId: "1" },
  { id: "4", name: "Kota Langsa", provinceId: "1" },
  { id: "5", name: "Kabupaten Aceh Barat", provinceId: "1" },
  { id: "6", name: "Kabupaten Aceh Besar", provinceId: "1" },
  { id: "7", name: "Kabupaten Aceh Timur", provinceId: "1" },
  { id: "8", name: "Kabupaten Aceh Utara", provinceId: "1" },
  { id: "9", name: "Kabupaten Aceh Tengah", provinceId: "1" },
  { id: "10", name: "Kabupaten Aceh Selatan", provinceId: "1" },
  { id: "11", name: "Kota Denpasar", provinceId: "2" },
  { id: "12", name: "Kabupaten Badung", provinceId: "2" },
  { id: "13", name: "Kabupaten Gianyar", provinceId: "2" },
  { id: "14", name: "Kabupaten Buleleng", provinceId: "2" },
  { id: "15", name: "Kabupaten Tabanan", provinceId: "2" },
  { id: "16", name: "Kabupaten Karangasem", provinceId: "2" },
  { id: "17", name: "Kota Tangerang", provinceId: "3" },
  { id: "18", name: "Kota Tangerang Selatan", provinceId: "3" },
  { id: "19", name: "Kota Cilegon", provinceId: "3" },
  { id: "20", name: "Kabupaten Tangerang", provinceId: "3" },
  { id: "21", name: "Kabupaten Serang", provinceId: "3" },
  { id: "22", name: "Kabupaten Lebak", provinceId: "3" },
  { id: "23", name: "Kota Serang", provinceId: "3" },
  { id: "24", name: "Kabupaten Pandeglang", provinceId: "3" },
  { id: "25", name: "Kota Bengkulu", provinceId: "4" },
  { id: "26", name: "Kabupaten Bengkulu Selatan", provinceId: "4" },
  { id: "27", name: "Kabupaten Bengkulu Utara", provinceId: "4" },
  { id: "28", name: "Kota Yogyakarta", provinceId: "5" },
  { id: "29", name: "Kabupaten Sleman", provinceId: "5" },
  { id: "30", name: "Kabupaten Bantul", provinceId: "5" },
  { id: "31", name: "Kabupaten Gunung Kidul", provinceId: "5" },
  { id: "32", name: "Kabupaten Kulon Progo", provinceId: "5" },
  { id: "33", name: "Kota Jakarta Pusat", provinceId: "6" },
  { id: "34", name: "Kota Jakarta Utara", provinceId: "6" },
  { id: "35", name: "Kota Jakarta Selatan", provinceId: "6" },
  { id: "36", name: "Kota Jakarta Timur", provinceId: "6" },
  { id: "37", name: "Kota Jakarta Barat", provinceId: "6" },
  { id: "38", name: "Kabupaten Kepulauan Seribu", provinceId: "6" },
  { id: "39", name: "Kota Gorontalo", provinceId: "7" },
  { id: "40", name: "Kabupaten Gorontalo", provinceId: "7" },
  { id: "41", name: "Kota Jambi", provinceId: "8" },
  { id: "42", name: "Kabupaten Muaro Jambi", provinceId: "8" },
  { id: "43", name: "Kabupaten Batanghari", provinceId: "8" },
  { id: "44", name: "Kabupaten Kerinci", provinceId: "8" },
  { id: "45", name: "Kota Bandung", provinceId: "9" },
  { id: "46", name: "Kota Bogor", provinceId: "9" },
  { id: "47", name: "Kota Bekasi", provinceId: "9" },
  { id: "48", name: "Kota Depok", provinceId: "9" },
  { id: "49", name: "Kota Cimahi", provinceId: "9" },
  { id: "50", name: "Kota Tasikmalaya", provinceId: "9" },
  { id: "51", name: "Kota Banjar", provinceId: "9" },
  { id: "52", name: "Kabupaten Bandung", provinceId: "9" },
  { id: "53", name: "Kabupaten Bogor", provinceId: "9" },
  { id: "54", name: "Kabupaten Bekasi", provinceId: "9" },
  { id: "55", name: "Kabupaten Cianjur", provinceId: "9" },
  { id: "56", name: "Kabupaten Garut", provinceId: "9" },
  { id: "57", name: "Kabupaten Indramayu", provinceId: "9" },
  { id: "58", name: "Kabupaten Karawang", provinceId: "9" },
  { id: "59", name: "Kabupaten Purwakarta", provinceId: "9" },
  { id: "60", name: "Kabupaten Subang", provinceId: "9" },
  { id: "61", name: "Kabupaten Sukabumi", provinceId: "9" },
  { id: "62", name: "Kabupaten Sumedang", provinceId: "9" },
  { id: "63", name: "Kabupaten Cirebon", provinceId: "9" },
  { id: "64", name: "Kota Cirebon", provinceId: "9" },
  { id: "65", name: "Kabupaten Bandung Barat", provinceId: "9" },
  { id: "66", name: "Kota Semarang", provinceId: "10" },
  { id: "67", name: "Kota Surakarta (Solo)", provinceId: "10" },
  { id: "68", name: "Kota Pekalongan", provinceId: "10" },
  { id: "69", name: "Kota Tegal", provinceId: "10" },
  { id: "70", name: "Kota Salatiga", provinceId: "10" },
  { id: "71", name: "Kabupaten Banyumas", provinceId: "10" },
  { id: "72", name: "Kabupaten Cilacap", provinceId: "10" },
  { id: "73", name: "Kabupaten Kendal", provinceId: "10" },
  { id: "74", name: "Kabupaten Pati", provinceId: "10" },
  { id: "75", name: "Kabupaten Pekalongan", provinceId: "10" },
  { id: "76", name: "Kabupaten Pemalang", provinceId: "10" },
  { id: "77", name: "Kabupaten Semarang", provinceId: "10" },
  { id: "78", name: "Kabupaten Sragen", provinceId: "10" },
  { id: "79", name: "Kabupaten Sukoharjo", provinceId: "10" },
  { id: "80", name: "Kabupaten Tegal", provinceId: "10" },
  { id: "81", name: "Kabupaten Wonogiri", provinceId: "10" },
  { id: "82", name: "Kabupaten Wonosobo", provinceId: "10" },
  { id: "83", name: "Kabupaten Magelang", provinceId: "10" },
  { id: "84", name: "Kota Magelang", provinceId: "10" },
  { id: "85", name: "Kabupaten Brebes", provinceId: "10" },
  { id: "86", name: "Kota Surabaya", provinceId: "11" },
  { id: "87", name: "Kota Malang", provinceId: "11" },
  { id: "88", name: "Kota Kediri", provinceId: "11" },
  { id: "89", name: "Kota Blitar", provinceId: "11" },
  { id: "90", name: "Kota Madiun", provinceId: "11" },
  { id: "91", name: "Kota Mojokerto", provinceId: "11" },
  { id: "92", name: "Kota Pasuruan", provinceId: "11" },
  { id: "93", name: "Kota Probolinggo", provinceId: "11" },
  { id: "94", name: "Kota Batu", provinceId: "11" },
  { id: "95", name: "Kabupaten Malang", provinceId: "11" },
  { id: "96", name: "Kabupaten Sidoarjo", provinceId: "11" },
  { id: "97", name: "Kabupaten Gresik", provinceId: "11" },
  { id: "98", name: "Kabupaten Banyuwangi", provinceId: "11" },
  { id: "99", name: "Kabupaten Jember", provinceId: "11" },
  { id: "100", name: "Kabupaten Kediri", provinceId: "11" },
  { id: "101", name: "Kabupaten Madiun", provinceId: "11" },
  { id: "102", name: "Kabupaten Mojokerto", provinceId: "11" },
  { id: "103", name: "Kabupaten Pasuruan", provinceId: "11" },
  { id: "104", name: "Kabupaten Probolinggo", provinceId: "11" },
  { id: "105", name: "Kabupaten Tuban", provinceId: "11" },
  { id: "106", name: "Kabupaten Bojonegoro", provinceId: "11" },
  { id: "107", name: "Kabupaten Lamongan", provinceId: "11" },
  { id: "108", name: "Kabupaten Nganjuk", provinceId: "11" },
  { id: "109", name: "Kabupaten Ponorogo", provinceId: "11" },
  { id: "110", name: "Kabupaten Sumenep", provinceId: "11" },
  { id: "111", name: "Kota Pontianak", provinceId: "12" },
  { id: "112", name: "Kota Singkawang", provinceId: "12" },
  { id: "113", name: "Kabupaten Pontianak", provinceId: "12" },
  { id: "114", name: "Kabupaten Kubu Raya", provinceId: "12" },
  { id: "115", name: "Kabupaten Sambas", provinceId: "12" },
  { id: "116", name: "Kota Banjarmasin", provinceId: "13" },
  { id: "117", name: "Kota Banjarbaru", provinceId: "13" },
  { id: "118", name: "Kabupaten Banjar", provinceId: "13" },
  { id: "119", name: "Kabupaten Tanah Laut", provinceId: "13" },
  { id: "120", name: "Kabupaten Barito Kuala", provinceId: "13" },
  { id: "121", name: "Kota Palangka Raya", provinceId: "14" },
  { id: "122", name: "Kabupaten Kapuas", provinceId: "14" },
  { id: "123", name: "Kabupaten Kotawaringin Timur", provinceId: "14" },
  { id: "124", name: "Kabupaten Kotawaringin Barat", provinceId: "14" },
  { id: "125", name: "Kota Samarinda", provinceId: "15" },
  { id: "126", name: "Kota Balikpapan", provinceId: "15" },
  { id: "127", name: "Kota Bontang", provinceId: "15" },
  { id: "128", name: "Kabupaten Kutai Kartanegara", provinceId: "15" },
  { id: "129", name: "Kabupaten Paser", provinceId: "15" },
  { id: "130", name: "Kota Tarakan", provinceId: "16" },
  { id: "131", name: "Kabupaten Bulungan", provinceId: "16" },
  { id: "132", name: "Kabupaten Nunukan", provinceId: "16" },
  { id: "133", name: "Kota Pangkal Pinang", provinceId: "17" },
  { id: "134", name: "Kabupaten Bangka", provinceId: "17" },
  { id: "135", name: "Kabupaten Bangka Barat", provinceId: "17" },
  { id: "136", name: "Kota Tanjung Pinang", provinceId: "18" },
  { id: "137", name: "Kota Batam", provinceId: "18" },
  { id: "138", name: "Kabupaten Bintan", provinceId: "18" },
  { id: "139", name: "Kabupaten Karimun", provinceId: "18" },
  { id: "140", name: "Kota Bandar Lampung", provinceId: "19" },
  { id: "141", name: "Kota Metro", provinceId: "19" },
  { id: "142", name: "Kabupaten Lampung Selatan", provinceId: "19" },
  { id: "143", name: "Kabupaten Lampung Tengah", provinceId: "19" },
  { id: "144", name: "Kabupaten Lampung Timur", provinceId: "19" },
  { id: "145", name: "Kabupaten Lampung Utara", provinceId: "19" },
  { id: "146", name: "Kota Ambon", provinceId: "20" },
  { id: "147", name: "Kabupaten Maluku Tengah", provinceId: "20" },
  { id: "148", name: "Kabupaten Seram Bagian Barat", provinceId: "20" },
  { id: "149", name: "Kota Ternate", provinceId: "21" },
  { id: "150", name: "Kota Tidore Kepulauan", provinceId: "21" },
  { id: "151", name: "Kabupaten Halmahera Barat", provinceId: "21" },
  { id: "152", name: "Kota Mataram", provinceId: "22" },
  { id: "153", name: "Kota Bima", provinceId: "22" },
  { id: "154", name: "Kabupaten Lombok Barat", provinceId: "22" },
  { id: "155", name: "Kabupaten Lombok Tengah", provinceId: "22" },
  { id: "156", name: "Kabupaten Lombok Timur", provinceId: "22" },
  { id: "157", name: "Kota Kupang", provinceId: "23" },
  { id: "158", name: "Kabupaten Timor Tengah Selatan", provinceId: "23" },
  { id: "159", name: "Kabupaten Flores Timur", provinceId: "23" },
  { id: "160", name: "Kabupaten Sikka", provinceId: "23" },
  { id: "161", name: "Kota Jayapura", provinceId: "24" },
  { id: "162", name: "Kabupaten Jayapura", provinceId: "24" },
  { id: "163", name: "Kabupaten Merauke", provinceId: "24" },
  { id: "164", name: "Kota Sorong", provinceId: "25" },
  { id: "165", name: "Kabupaten Sorong", provinceId: "25" },
  { id: "166", name: "Kabupaten Manokwari", provinceId: "25" },
  { id: "167", name: "Kota Pekanbaru", provinceId: "26" },
  { id: "168", name: "Kota Dumai", provinceId: "26" },
  { id: "169", name: "Kabupaten Kampar", provinceId: "26" },
  { id: "170", name: "Kabupaten Bengkalis", provinceId: "26" },
  { id: "171", name: "Kabupaten Siak", provinceId: "26" },
  { id: "172", name: "Kabupaten Rokan Hulu", provinceId: "26" },
  { id: "173", name: "Kabupaten Indragiri Hilir", provinceId: "26" },
  { id: "174", name: "Kota Mamuju", provinceId: "27" },
  { id: "175", name: "Kabupaten Majene", provinceId: "27" },
  { id: "176", name: "Kabupaten Polewali Mandar", provinceId: "27" },
  { id: "177", name: "Kota Makassar", provinceId: "28" },
  { id: "178", name: "Kota Parepare", provinceId: "28" },
  { id: "179", name: "Kota Palopo", provinceId: "28" },
  { id: "180", name: "Kabupaten Gowa", provinceId: "28" },
  { id: "181", name: "Kabupaten Maros", provinceId: "28" },
  { id: "182", name: "Kabupaten Bone", provinceId: "28" },
  { id: "183", name: "Kabupaten Wajo", provinceId: "28" },
  { id: "184", name: "Kota Palu", provinceId: "29" },
  { id: "185", name: "Kabupaten Donggala", provinceId: "29" },
  { id: "186", name: "Kabupaten Poso", provinceId: "29" },
  { id: "187", name: "Kabupaten Banggai", provinceId: "29" },
  { id: "188", name: "Kota Kendari", provinceId: "30" },
  { id: "189", name: "Kota Bau-Bau", provinceId: "30" },
  { id: "190", name: "Kabupaten Konawe", provinceId: "30" },
  { id: "191", name: "Kabupaten Kolaka", provinceId: "30" },
  { id: "192", name: "Kota Manado", provinceId: "31" },
  { id: "193", name: "Kota Bitung", provinceId: "31" },
  { id: "194", name: "Kota Tomohon", provinceId: "31" },
  { id: "195", name: "Kota Kotamobagu", provinceId: "31" },
  { id: "196", name: "Kabupaten Minahasa", provinceId: "31" },
  { id: "197", name: "Kota Padang", provinceId: "32" },
  { id: "198", name: "Kota Bukittinggi", provinceId: "32" },
  { id: "199", name: "Kota Payakumbuh", provinceId: "32" },
  { id: "200", name: "Kota Padang Panjang", provinceId: "32" },
  { id: "201", name: "Kota Sawahlunto", provinceId: "32" },
  { id: "202", name: "Kabupaten Agam", provinceId: "32" },
  { id: "203", name: "Kabupaten Tanah Datar", provinceId: "32" },
  { id: "204", name: "Kabupaten Padang Pariaman", provinceId: "32" },
  { id: "205", name: "Kota Pariaman", provinceId: "32" },
  { id: "206", name: "Kota Palembang", provinceId: "33" },
  { id: "207", name: "Kota Prabumulih", provinceId: "33" },
  { id: "208", name: "Kota Lubuklinggau", provinceId: "33" },
  { id: "209", name: "Kota Pagar Alam", provinceId: "33" },
  { id: "210", name: "Kabupaten Banyuasin", provinceId: "33" },
  { id: "211", name: "Kabupaten Musi Banyuasin", provinceId: "33" },
  { id: "212", name: "Kabupaten Ogan Komering Ilir", provinceId: "33" },
  { id: "213", name: "Kabupaten Ogan Komering Ulu", provinceId: "33" },
  { id: "214", name: "Kota Medan", provinceId: "34" },
  { id: "215", name: "Kota Binjai", provinceId: "34" },
  { id: "216", name: "Kota Pematangsiantar", provinceId: "34" },
  { id: "217", name: "Kota Tebing Tinggi", provinceId: "34" },
  { id: "218", name: "Kota Padang Sidempuan", provinceId: "34" },
  { id: "219", name: "Kota Gunungsitoli", provinceId: "34" },
  { id: "220", name: "Kota Tanjungbalai", provinceId: "34" },
  { id: "221", name: "Kota Sibolga", provinceId: "34" },
  { id: "222", name: "Kabupaten Deli Serdang", provinceId: "34" },
  { id: "223", name: "Kabupaten Langkat", provinceId: "34" },
  { id: "224", name: "Kabupaten Simalungun", provinceId: "34" },
  { id: "225", name: "Kabupaten Toba Samosir", provinceId: "34" },
  { id: "226", name: "Kabupaten Karo", provinceId: "34" },
  { id: "227", name: "Kabupaten Asahan", provinceId: "34" },
  { id: "228", name: "Kabupaten Labuhanbatu", provinceId: "34" },
  { id: "229", name: "Kota Nabire", provinceId: "35" },
  { id: "230", name: "Kabupaten Mimika", provinceId: "35" },
  { id: "231", name: "Kota Wamena", provinceId: "36" },
  { id: "232", name: "Kabupaten Jayawijaya", provinceId: "36" },
  { id: "233", name: "Kabupaten Merauke", provinceId: "37" },
  { id: "234", name: "Kabupaten Boven Digoel", provinceId: "37" },
  { id: "235", name: "Kota Sorong", provinceId: "38" },
  { id: "236", name: "Kabupaten Tambrauw", provinceId: "38" },
]
